// @ts-check

export function getElements(){
  return {
    // tabs/views
    tabToday: document.getElementById("tabToday"),
    tabHistory: document.getElementById("tabHistory"),
    tabReview: document.getElementById("tabReview"),
    tabSettings: document.getElementById("tabSettings"),
    outboxBadge: document.getElementById("outboxBadge"),
    viewToday: document.getElementById("viewToday"),
    viewHistory: document.getElementById("viewHistory"),
    viewReview: document.getElementById("viewReview"),
    viewSettings: document.getElementById("viewSettings"),

    // header
    syncStatus: document.getElementById("syncStatus"),

    // today head
    prevDay: document.getElementById("prevDay"),
    nextDay: document.getElementById("nextDay"),
    datePicker: document.getElementById("datePicker"),
    copyYesterday: document.getElementById("copyYesterday"),
    phaseLabel: document.getElementById("phaseLabel"),
    phaseSub: document.getElementById("phaseSub"),
    toggleFocus: document.getElementById("toggleFocus"),
    focusLabel: document.getElementById("focusLabel"),

    // timeline
    timelineTrack: document.getElementById("timelineTrack"),
    nowMarker: document.getElementById("nowMarker"),
    futureFog: document.getElementById("futureFog"),

    sunArc: document.getElementById("sunArc"),
    sunDot: document.getElementById("sunDot"),
    sunGlow: document.getElementById("sunGlow"),
    sunTime: document.getElementById("sunTime"),
    currentTime: document.getElementById("currentTime"),
    currentTz: document.getElementById("currentTz"),

    // rituals
    movedBeforeLunch: document.getElementById("movedBeforeLunch"),
    trained: document.getElementById("trained"),
    highFatDay: document.getElementById("highFatDay"),
    moveSub: document.getElementById("moveSub"),
    trainSub: document.getElementById("trainSub"),
    fatDaySub: document.getElementById("fatDaySub"),

    // signals
    energyScale: document.getElementById("energyScale"),
    moodScale: document.getElementById("moodScale"),
    cravingsScale: document.getElementById("cravingsScale"),

    todayNudge: document.getElementById("todayNudge"),
    todayNudgeTitle: document.getElementById("todayNudgeTitle"),
    todayNudgeMessage: document.getElementById("todayNudgeMessage"),
    todayNudgeReason: document.getElementById("todayNudgeReason"),
    todayNudgeDismiss: document.getElementById("todayNudgeDismiss"),

    // daily notes
    notes: document.getElementById("notes"),
    notesBlock: document.getElementById("notesBlock"),
    redactionBanner: document.getElementById("redactionBanner"),
    fabEdit: document.getElementById("fabEdit"),
    appLockOverlay: document.getElementById("appLockOverlay"),
    appLockInput: document.getElementById("appLockInput"),
    appLockSubmit: document.getElementById("appLockSubmit"),
    appLockMessage: document.getElementById("appLockMessage"),
    supplementsPanel: document.getElementById("supplementsPanel"),
    supplementsModeLabel: document.getElementById("supplementsModeLabel"),
    supplementsChips: document.getElementById("supplementsChips"),
    supplementsNotes: document.getElementById("supplementsNotes"),

    // history
    historyList: document.getElementById("historyList"),
    historySearch: document.getElementById("historySearch"),
    historyFilters: document.getElementById("historyFilters"),
    exportBtn: document.getElementById("exportBtn"),
    exportAltBtn: document.getElementById("exportAltBtn"),
    exportCsvBtn: document.getElementById("exportCsvBtn"),
    importFile: document.getElementById("importFile"),
    importMode: document.getElementById("importMode"),
    importApply: document.getElementById("importApply"),
    importStatus: document.getElementById("importStatus"),
    diagStorageMode: document.getElementById("diagStorageMode"),
    diagPersistStatus: document.getElementById("diagPersistStatus"),
    diagSyncStatus: document.getElementById("diagSyncStatus"),
    diagOutboxDepth: document.getElementById("diagOutboxDepth"),
    diagConflictCount: document.getElementById("diagConflictCount"),
    diagLastError: document.getElementById("diagLastError"),
    diagSafeMode: document.getElementById("diagSafeMode"),
    diagDstClamp: document.getElementById("diagDstClamp"),
    diagSchemaVersion: document.getElementById("diagSchemaVersion"),
    diagAppVersion: document.getElementById("diagAppVersion"),
    diagInstallId: document.getElementById("diagInstallId"),
    diagSnapshotCount: document.getElementById("diagSnapshotCount"),
    diagMissingItems: document.getElementById("diagMissingItems"),
    safeModeBanner: document.getElementById("safeModeBanner"),
    safeModeExport: document.getElementById("safeModeExport"),
    auditFilter: document.getElementById("auditFilter"),
    auditLogList: document.getElementById("auditLogList"),
    snapshotCreate: document.getElementById("snapshotCreate"),
    snapshotList: document.getElementById("snapshotList"),
    perfLogToggle: document.getElementById("perfLogToggle"),
    reviewRange: document.getElementById("reviewRange"),
    reviewPrevWeek: document.getElementById("reviewPrevWeek"),
    reviewTodayWeek: document.getElementById("reviewTodayWeek"),
    reviewNextWeek: document.getElementById("reviewNextWeek"),
    reviewSummary: document.getElementById("reviewSummary"),
    reviewPhase: document.getElementById("reviewPhase"),
    reviewIssues: document.getElementById("reviewIssues"),
    reviewCorrelations: document.getElementById("reviewCorrelations"),
    reviewInsights: document.getElementById("reviewInsights"),
    coverageMatrix: document.getElementById("coverageMatrix"),
    rotationPicks: document.getElementById("rotationPicks"),

    undoToast: document.getElementById("undoToast"),
    undoLabel: document.getElementById("undoLabel"),
    undoAction: document.getElementById("undoAction"),

    // settings
    setDayStart: document.getElementById("setDayStart"),
    setDayEnd: document.getElementById("setDayEnd"),
    setFtnEnd: document.getElementById("setFtnEnd"),
    setLunchEnd: document.getElementById("setLunchEnd"),
    setDinnerEnd: document.getElementById("setDinnerEnd"),
    setSunrise: document.getElementById("setSunrise"),
    setSunset: document.getElementById("setSunset"),
    setSunMode: document.getElementById("setSunMode"),
    sunAutoBtn: document.getElementById("sunAutoBtn"),
    sunAutoStatus: document.getElementById("sunAutoStatus"),
    setPhase: document.getElementById("setPhase"),
    setFocusMode: document.getElementById("setFocusMode"),
    setWeekStart: document.getElementById("setWeekStart"),
    setSupplementsMode: document.getElementById("setSupplementsMode"),
    saveSettings: document.getElementById("saveSettings"),
    resetToday: document.getElementById("resetToday"),
    syncLinkInput: document.getElementById("syncLinkInput"),
    syncLinkApply: document.getElementById("syncLinkApply"),
    syncLinkCopy: document.getElementById("syncLinkCopy"),
    syncLinkStatus: document.getElementById("syncLinkStatus"),
    syncStatusLine: document.getElementById("syncStatusLine"),
    syncE2eeToggle: document.getElementById("syncE2eeToggle"),
    syncMode: document.getElementById("syncMode"),
    syncEndpoint: document.getElementById("syncEndpoint"),
    syncNowBtn: document.getElementById("syncNowBtn"),
    syncResetSpace: document.getElementById("syncResetSpace"),
    privacyAppLockToggle: document.getElementById("privacyAppLockToggle"),
    appLockSetBtn: document.getElementById("appLockSetBtn"),
    privacyBlurToggle: document.getElementById("privacyBlurToggle"),
    privacyRedactToggle: document.getElementById("privacyRedactToggle"),
    privacyEncryptedToggle: document.getElementById("privacyEncryptedToggle"),
    privacyBlurOverlay: document.getElementById("privacyBlurOverlay"),
    todayNudgeToggle: document.getElementById("todayNudgeToggle"),

    rosterProteins: document.getElementById("roster-proteins"),
    rosterCarbs: document.getElementById("roster-carbs"),
    rosterFats: document.getElementById("roster-fats"),
    rosterMicros: document.getElementById("roster-micros"),
    rosterSupplements: document.getElementById("roster-supplements"),
    rosterSupplementsBlock: document.getElementById("roster-supplements-block"),

    // sheet
    sheet: document.getElementById("sheet"),
    sheetBackdrop: document.getElementById("sheetBackdrop"),
    closeSheet: document.getElementById("closeSheet"),
    doneSegment: document.getElementById("doneSegment"),
    clearSegment: document.getElementById("clearSegment"),
    sheetTitle: document.getElementById("sheetTitle"),
    sheetSub: document.getElementById("sheetSub"),
    sheetWindowLabel: document.getElementById("sheetWindowLabel"),
    sheetWindowTime: document.getElementById("sheetWindowTime"),
    sheetProgress: document.getElementById("sheetProgress"),
    ftnModeRow: document.getElementById("ftnModeRow"),
    ftnModeSeg: document.getElementById("ftnModeSeg"),

    searchProteins: document.getElementById("searchProteins"),
    searchCarbs: document.getElementById("searchCarbs"),
    searchFats: document.getElementById("searchFats"),
    searchMicros: document.getElementById("searchMicros"),

    chipsProteins: document.getElementById("chipsProteins"),
    chipsCarbs: document.getElementById("chipsCarbs"),
    chipsFats: document.getElementById("chipsFats"),
    chipsMicros: document.getElementById("chipsMicros"),
    addProtein: document.getElementById("addProtein"),
    addCarb: document.getElementById("addCarb"),
    addFat: document.getElementById("addFat"),
    addMicro: document.getElementById("addMicro"),

    segCollision: document.getElementById("segCollision"),
    segHighFat: document.getElementById("segHighFat"),
    segSeedOil: document.getElementById("segSeedOil"),
    segStatus: document.getElementById("segStatus"),
    segNotes: document.getElementById("segNotes"),
    flagHelp: document.getElementById("flagHelp")
  };
}
